Fixed dev mode not running after introducing `exec` method (#536)
* Fixed dev mode not running

Uncaught TypeError: window.requireElectron is not a function

* CI / CD - Format Updates Automatic Commit  [skip ci]

Co-authored-by: synle <synle@users.noreply.github.com>